"""Creada tabla global para las imagenes, se agregan campos para especificar el origen (src) de la imagen, asi como su tipo (local o externa), nombre y pie de foto

Revision ID: 026c9b5af4b6
Revises: e76353ff468f
Create Date: 2024-11-09 23:32:50.909741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026c9b5af4b6'
down_revision = 'e76353ff468f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('src', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('archivo', 'url', name='tipo'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('caption', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image')
    # ### end Alembic commands ###
